openapi: 3.0.0
info:
  title: Заказ ресурсов на облаке
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1/
    description: Dev server
paths:
  /clouds:
    get:
      summary: Метод получения списка ресурсов на облако
      tags:
        - Clouds
      operationId: getAllClouds
      parameters:
        - name: cloudID
          in: query
          description: ID of Cloud to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Успешный ответ со списком ресурсов в облаке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Всё остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Создание заказа на облако
      tags:
        - Clouds
      operationId: createCloud
      requestBody:
        content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      responses:
        "200":
          description: Успешный ответ со списком ресурсов в облаке
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        "default":
          description: Всё остальное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      tags:
        - Clouds
      summary: Отмена заказа на облако
      operationId: cancelCreateCloud
      parameters:
        - name: cloudID
          in: query
          description: ID of Cloud to cancel
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '400':
          description: Предложен некорректный ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
        '404':
          description: Заказ не найден
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Clouds"
components:
  schemas:
    Cloud:
      type: object
      required:
        - id_client
        - OS
        - RAM
        - CPU
        - HDD
      properties:
        cloud_id:
          type: string
          example: f1o2b615
        client_id:
          type: string
          example: f1o2b615
        OS:
          type: string
          enum:
            - Windows
            - Linux
          description: Операционная система сервера
        RAM:
          type: string
          example: 128
          description: Объём оперативной памяти
        CPU:
          type: string
          example: 8
          description: Количество ядер процессора
        HDD:
          type: string
          example: 512
          description: Объём жесткого диска Гб
    Clouds:
      type: array
      items:
        $ref: "#/components/schemas/Cloud"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
